version: '2'
services:
  api:
    build: .
    image: gowebapp
    restart: always
    ports:
      - 8080:8080
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: goland

    volumes:
      - ./db/pgdata:/pgdata